name: Build, Test and Deploy Landing Page

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # Set up Node.js
    - name: Install nodejs for npm
      uses: actions/setup-node@v4
      with:
        node-version: "23.6.0"
        cache: "npm"

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Build the app
    - name: Build
      run: npm run build

    # Set up Docker Buildx
    - name: Set up QEMU and Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        install: true

    # Login to Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_KEY }}

    # Build and push Docker image
    - name: Build and Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/landing-page:latest
        platforms: linux/arm64
