name: Build, Test and Deploy Landing Page

on:
  push:
    branches:
    - main

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install nodejs for npm
      uses: actions/setup-node@v4
      with:
        node-version: "23.6.0"
        cache: "npm"

    - name: Install dependencies
      run: npm install

    - name: Build
      run: npm run build

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/landing-page:latest
        platforms: linux/amd64,linux/arm64

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_KEY }}

    - name: Push Docker image
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/landing-page:latest
