name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services: [ backend, frontend ]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_KEY }}

    - name: Build and Push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: ./${{ matrix.services }}/Dockerfile
        push: true
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/landing-page-${{ matrix.services }}:latest
          ${{ secrets.DOCKERHUB_USERNAME }}/landing-page-${{ matrix.services }}:${{ github.sha }}
        platforms: linux/arm64,linux/amd64
